# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true # To reduce noise with GitHub's diffs; violations render as 🚫 at the end of a file

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Style/StringLiterals:
  Enabled: false # Too heavy-handed to enforce for students
